#!/usr/bin/perl -w

use strict;
use warnings;
use lib 'lib';

use Language::P::Parrot::BootstrapRuntime;
use Language::P::Parrot::Generator;
use Language::P;

my $parrot_path = '%PARROT%';
my $runtime = Language::P::Parrot::BootstrapRuntime->new
                  ( { parrot => $parrot_path,
                      } );
my $generator = Language::P::Parrot::Generator->new( { runtime => $runtime,
                                                       parrot  => $parrot_path,
                                                       } );
my $p = Language::P->new_from_argv( \@ARGV,
                                    { runtime   => $runtime,
                                      generator => $generator,
                                      } );
$generator->file_name( $p->program . '.pbc' );

$p->run;
